### ISSUE TITLE
CSS Update: Typography and Images

### ISSUE THREAD

**Issue by takuyakikuchi** [takuyakikuchi/wine-blog#104]
## Goals

Apply some of the learnings from https://courses.joshwcomeau.com/css-for-js/06-typography-and-media/01-introduction

## Todos

- [x] ~~Use `hyphens: auto`~~
- [x] ~~Use Text Overflow~~
- [x] ~~Utilize [Fontsource | Home](https://fontsource.org/docs/introduction)~~
- [x] ~~Try `font-display`~~
- [x] ~~Consider whether font variable can be used~~
- [x] Use Icons in the app
- [x] Check image alt-text
- [x] ~~Download google font and read it from local~~
- [x] `object-fit: cover;`

## References

- https://courses.joshwcomeau.com/css-for-js/06-typography-and-media/01-introduction
- [Fontsource | Home](https://fontsource.org/docs/introduction)

## Other notes
