### ISSUE TITLE
Google Analysis

### ISSUE THREAD

**Issue by takuyakikuchi** [takuyakikuchi/wine-blog#26]
## Goals

- Add Google Analysis to the page
- Update footer to inform visitors about Google analytics being used

## Todos

- [x] Create GA account
- [x] Add the tracking snippet
	- [x] Global site site tag
	- [x] preview function
	- [x] event function
- [x] Add private policy
- [x] Update README

## References

- [next.js example app](https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics)
- [サイトに gtag.js を追加する  |  ウェブ向けユニバーサル アナリティクス（gtag.js）  |  Google Developers](https://developers.google.com/analytics/devguides/collection/gtagjs)
- [Next.jsでGoogle Analyticsを使えるようにする - パンダのプログラミングブログ](https://panda-program.com/posts/nextjs-google-analytics)

## Other notes
