### ISSUE TITLE
Implement Lighthouse

### ISSUE THREAD

**Issue by takuyakikuchi** [takuyakikuchi/wine-blog#79]
Todo
- [x] Install Lighthouse CI to Github Actions
- [x] Set the generated token in the repository setting
- [x] Add Github Action setting file: `.github/workflows/lighthouse.yml`
- [x] Add Lightouse CI setting file in the root of the project
- [ ] ~~Update scripts in `package.json`~~
- [x] build failed with microCMS creat
- [x] Update `!draftkey` case in `preview.ts`
- [x] lighthouse ci configuration on pages to check
	- [x] `--numberOfRuns`

Memo
- Lightouse: Web site quality evaluation software by Google
- Github Actions: CI/CD service by Github

Reference
- [Github Actions × Lighthouse CI を Next.js プロジェクトに導入する – kimizuy blog](https://blog.kimizuy.dev/posts/add-lhci-to-nextjs)
- [GoogleChrome/lighthouse-ci: Automate running Lighthouse for every commit, viewing the changes, and preventing regressions](https://github.com/GoogleChrome/lighthouse-ci)
- [lighthouse-ci/getting-started.md at main · GoogleChrome/lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md)

**Comment by takuyakikuchi** [comment]
Pkcah6apFT1tIyT:22751684:ifRDhEO59
