### ISSUE TITLE
Refactoring: Responsive and Behavioural CSS

### ISSUE THREAD

**Issue by takuyakikuchi** [takuyakikuchi/wine-blog#87]
## What to achieve

Apply some of the techniques covered in "Responsive and Behavioural CSS"
https://courses.joshwcomeau.com/css-for-js/05-responsive-css/01-introduction

## Todos

- [x] Switching from desktop-first media query approach to mobile-first
- [x] Set reasonable breakpoints for the responsive design
- [x] Utilize css variables
- [x] Check if `clamp`, `min`, or `max` can be used
- [x] Check the size of typography
- [x] Change header responsible strategy from the media query to the fluid design
- [x] Check the usage of styled-components theming

## References
- https://courses.joshwcomeau.com/css-for-js/05-responsive-css

### Typography size check

- [x] Body text should stay the same size across all devices.
- [x] Body text should at least 16px.
- [x] Header font size should be responsive.
